### ISSUE TITLE
Update docker-compose.override.yml traefik labels and limit subdomains to "a-z"

### ISSUE THREAD

**Issue by capynet** [frontid/dockerizer#78]
```
    labels:
      # Our traefik needs the exact name instead just "apache" since
      # it holds many containters and each one has it own unique name.
      traefik.backend: ${PROJECT_NAME}_apache

      # Minimal modifications to allow subdomain wildcard. Any URL that does not match with
      # taken domains like pma."project".localhost will fall intro apache container.
      traefik.frontend.rule: HostRegexp:${PROJECT_BASE_URL}, {subdomain:[a-z]+}.${PROJECT_BASE_URL}
```
