### ISSUE TITLE
Allow .docker.env define new domains + port + container

### ISSUE THREAD

**Issue by capynet** [frontid/dockerizer#79]
# Use case
I have two node apps that runs at 8888 and 9999 ports. I would like to have access trough `8888.mysite.localhost` and `9999.mysite.localhost` (pointing to the frontend container).

# Purposed solution
Add `CUSTOM_PORTS= 8888:frontend,9999:frontend` to .docker.env and split and use the pair port + container to construct labels at the corresponding container like this:

```
    labels:
      traefik.9999.frontend.rule: "Host:9999.${PROJECT_NAME}.localhost"
      traefik.9999.port: "9999"

      traefik.8888.frontend.rule: "Host:8888.${PROJECT_NAME}.localhost"
      traefik.8888.port: "8888"
```

It can be accomplished adding some params via CLI?
